project: linebot-test3
runtime: python
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

version: 1
api_version: 1
threadsafe: yes

handlers:
- url: /worker
  script: main.app
  login: admin
  secure: always

- url: .*
  script: main.app
  secure: always
