project: linebot-test1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /worker
  script: main.app
  login: admin
  secure: always

- url: .*
  script: main.app
  secure: always

beta_settings:
      cloud_sql_instances: "linebot-test1:us-central1:linebot-test1"
